const app=document.getElementById("app");
const tg=window.Telegram?.WebApp;if(tg){try{tg.ready();tg.expand()}catch(e){}}
const state={screen:"home",topic:null,context:"",card:null,cardRevealed:false,showCard:false,draftAnswer:"",questions:[],qIndex:0,answers:[],history:loadHistory()};
const cards=[
{id:1,name:"Отдых",page:1,row:0,col:0,topics:["desires","anxiety","curiosity"]},
{id:2,name:"Окно",page:1,row:0,col:1,topics:["repeat","curiosity"]},
{id:3,name:"Разговор",page:1,row:0,col:2,topics:["relationships","decision"]},
{id:4,name:"Дождь",page:1,row:0,col:3,topics:["anxiety","repeat"]},
{id:5,name:"Руки",page:1,row:0,col:4,topics:["relationships","decision"]},
{id:6,name:"Кухня",page:1,row:0,col:5,topics:["desires","relationships"]},
{id:7,name:"Огонь",page:1,row:1,col:0,topics:["anxiety","decision","repeat"]},
{id:8,name:"Десерт",page:1,row:1,col:1,topics:["desires","curiosity"]},
{id:9,name:"У окна",page:1,row:1,col:2,topics:["anxiety","curiosity"]},
{id:10,name:"Компания",page:1,row:1,col:3,topics:["relationships","curiosity"]},
{id:11,name:"Диван",page:1,row:1,col:4,topics:["relationships","repeat"]},
{id:12,name:"Дети",page:1,row:1,col:5,topics:["relationships","curiosity"]},
{id:13,name:"Наушники",page:1,row:2,col:0,topics:["desires","curiosity"]},
{id:14,name:"Покупки",page:1,row:2,col:1,topics:["decision","desires"]},
{id:15,name:"Сцена",page:1,row:2,col:2,topics:["desires","curiosity"]},
{id:16,name:"Пара",page:1,row:2,col:3,topics:["relationships","decision"]},
{id:17,name:"Чтение",page:1,row:2,col:4,topics:["curiosity","repeat"]},
{id:18,name:"Игра",page:1,row:2,col:5,topics:["curiosity","relationships"]}
];
function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function topicById(id){return TOPICS.find(t=>t.id===id)||TOPICS[5]}
function go(screen){state.screen=screen;state.showCard=false;state.draftAnswer="";render();window.scrollTo({top:0,behavior:"smooth"})}
function button(label,cls,action){return `<button class="${cls}" data-action="${action}">${label}</button>`}
function header(){return `<header class="topbar"><button class="brand" data-action="home">МАК</button><button class="history-link" data-action="history">История</button></header>`}
function render(){const views={home:renderHome,topic:renderTopic,context:renderContext,reveal:renderReveal,questions:renderQuestion,result:renderResult,history:renderHistory};app.innerHTML=views[state.screen]();bind();if(state.screen==="reveal"&&state.cardRevealed)drawCard("cardCanvas");if(state.screen==="questions")drawCard(state.showCard?"cardPreviewImg":"questionCardImg")}
function renderHome(){return `<div class="shell">${header()}<section class="hero"><div class="eyebrow">ИССЛЕДОВАНИЕ СЕБЯ</div><h1>Посмотри.<br>Заметь.<br>Пойми.</h1><p class="lead">Один образ. Несколько вопросов. И немного честного внимания к тому, что происходит внутри.</p></section><div class="home-action">${button("Начать исследование <span>→</span>","primary","start")}</div><button class="history-ghost" data-action="history">Моя история <span>↗</span></button><div class="home-note">Здесь нет правильного значения карты. Важны твои ассоциации, слова и то, как меняется твой взгляд.</div></div>`}
function renderTopic(){return `<div class="shell">${header()}<button class="back" data-action="home">← Назад</button><section class="page-head"><div class="eyebrow">01 / ТЕМА</div><h2>О чём хочется<br>подумать?</h2><p>Можно выбрать направление или просто позволить исследованию идти своим ходом.</p></section><div class="topic-list">${TOPICS.map((t,i)=>`<button class="topic" data-topic="${t.id}"><span class="topic-num">0${i+1}</span><span class="topic-main">${t.icon} ${esc(t.title)}</span><span class="topic-arrow">↗</span></button>`).join("")}</div></div>`}
function renderContext(){const t=topicById(state.topic);return `<div class="shell">${header()}<button class="back" data-action="topic">← Назад</button><section class="page-head"><div class="eyebrow">02 / КОНТЕКСТ</div><h2>Есть что-то,<br>о чём думаешь?</h2><p>Пара слов поможет сделать разговор ближе к твоей ситуации. Можно пропустить.</p></section><div class="dark-panel"><div class="panel-label">${t.icon} ${esc(t.title)}</div><textarea id="context" placeholder="Например: я не понимаю, стоит ли делать следующий шаг…">${esc(state.context)}</textarea><div class="panel-actions">${button("Продолжить →","primary","context-next")}${button("Пропустить","text-btn","context-skip")}</div></div></div>`}
function renderReveal(){return `<div class="shell reveal-shell">${header()}<section class="reveal-head"><div class="eyebrow">03 / ОБРАЗ</div><h2>${state.cardRevealed?"Твой образ":"Готов?"}</h2><p>${state.cardRevealed?"Не спеши. Посмотри на изображение и заметь первую реакцию.":"Сейчас появится случайный образ. Не ищи правильный ответ. Просто посмотри."}</p></section><div class="reveal-stage ${state.cardRevealed?'is-revealed':''}">${state.cardRevealed?'<div class="card-crop reveal-card"><img id="cardCanvas" class="card-image" alt="Случайный ассоциативный образ"></div>':'<div class="card-back"><span>МАК</span><small>ОБРАЗ</small></div>'}</div><div class="reveal-actions">${state.cardRevealed?button("Продолжить →","primary","continue"):button("Вытянуть карту","primary","draw")}</div></div>`}
function drawCard(targetId="cardCanvas"){const el=document.getElementById(targetId),src=window.MAK_PAGES?.[state.card?.page];if(!el||!src||!state.card)return;el.src=src;el.style.setProperty("--col",state.card.col);el.style.setProperty("--row",state.card.row)}
function renderQuestion(){const total=state.questions.length,q=state.questions[state.qIndex],pct=Math.round((state.qIndex/Math.max(1,total))*100);return `<div class="shell question-shell">${header()}<div class="question-meta"><span>ОБРАЗ / ${String(state.qIndex+1).padStart(2,"0")}</span><button class="card-memory" data-action="view-card" aria-label="Снова посмотреть карту">✦ <span>Посмотреть карту</span></button><span>${pct}%</span></div><div class="progress"><i style="width:${pct}%"></i></div><section class="question-page"><div class="eyebrow">СМОТРИМ НА ОБРАЗ</div><div class="question">${esc(q)}</div><div class="question-hint">Не ищи «правильный» ответ. Первая живая мысль подходит.</div><textarea id="answer" placeholder="Напиши, что приходит в голову…">${esc(state.draftAnswer)}</textarea><div class="question-bottom"><span>${state.answers.length?"Продолжай":"Начни с первой мысли"}</span>${button(state.qIndex===total-1?"Завершить →":"Дальше →","primary","answer-next")}</div></section>${state.showCard?`<div class="card-modal" data-action="close-card"><div class="card-modal-inner" data-stop="1"><button class="modal-close" data-action="close-card" aria-label="Закрыть">×</button><div class="modal-label">ТВОЙ ОБРАЗ</div><div class="card-crop modal-crop"><img id="cardPreviewImg" class="card-preview" alt="Твоя карта"></div><p>Посмотри ещё раз. Что замечаешь теперь?</p></div></div>`:`<div class="question-card-dock"><button class="card-dock" data-action="view-card"><span>✦</span><strong>Карта</strong><small>открыть снова</small></button><div class="card-crop mini-crop"><img id="questionCardImg" alt="Твоя карта"></div></div>`}</div>`}
function makeResult(){const text=state.answers.join(" "),w=text.toLowerCase(),has=(...a)=>a.some(x=>w.includes(x));let observation,contradiction,connection,question;if(has("контрол","провер","заранее","предусмотр","знать"))observation="В твоих ответах несколько раз появляется тема предсказуемости: тебе важно понять, что будет дальше, и заранее подготовиться.";else if(has("боюсь","страх","тревог","опас","неизвест"))observation="В рассказе заметно внимание к тому, что может пойти не так. При этом ты не только замечаешь напряжение, но и ищешь способ с ним обойтись.";else if(has("друг","отнош","близ","вместе","один"))observation="Ты часто возвращаешься к тому, как люди расположены друг к другу и чего они ждут друг от друга.";else observation="Важнее всего здесь то, как твой рассказ менялся: ты не просто описывал картинку, а постепенно добавлял ей историю и связь с собой.";const first=state.answers[0]||"",later=state.answers[Math.min(6,state.answers.length-1)]||"";contradiction=first&&later&&first.toLowerCase()!==later.toLowerCase()?`Сначала ты увидел образ как «${clip(first,70)}», а позже сместил внимание к «${clip(later,70)}». Между этими двумя взглядами есть интересное напряжение.`:"В твоих ответах есть место, которое пока не складывается в однозначную историю — и это может быть интереснее готового объяснения.";connection=state.context?`Ты пришёл с темой «${clip(state.context,90)}». В рассказе о карте она отзывается через собственные образы и действия, а не через готовое толкование карты.`:"Связь с жизнью появляется не из значения карты, а из того, какие слова и ситуации ты сам к ней привязал.";question=has("выбор","реш","шаг","сделать")?"Если это действительно похоже на твою ситуацию, какой следующий шаг ты выбираешь сам — даже если не можешь заранее знать его результат?":has("друг","отнош","ожида","близ")?"Что изменилось бы в этой истории, если бы тебе не нужно было угадывать, чего хочет другой человек?":"Что в этой истории ты обычно не замечаешь о себе — и что изменится, если заметить это сейчас?";return{observation,contradiction,connection,question}}
function clip(s,n){s=s.trim();return s.length>n?s.slice(0,n-1)+"…":s}
function renderResult(){const r=makeResult(),t=topicById(state.topic);return `<div class="shell result-shell">${header()}<section class="result-head"><div class="eyebrow">04 / ТВОЯ ИСТОРИЯ</div><h2>${esc(t.title)}</h2></section><div class="result-list"><article><div class="result-label">01 — Что интересно заметить</div><p>${esc(r.observation)}</p></article><article><div class="result-label">02 — Интересное противоречие</div><p>${esc(r.contradiction)}</p></article><article><div class="result-label">03 — Возможная связь</div><p>${esc(r.connection)}</p></article><article class="final-question"><div class="result-label">04 — Вопрос с собой</div><p>${esc(r.question)}</p></article></div><div class="result-actions">${button("Сохранить","primary","save")}${button("Поделиться","secondary","share")}${button("Исследовать ещё →","text-btn","restart")}</div><p class="disclaimer">Это не диагноз и не расшифровка карты. Это сборка наблюдений по твоим собственным ответам.</p></div>`}
function renderHistory(){return `<div class="shell">${header()}<button class="back" data-action="home">← На главную</button><section class="page-head"><div class="eyebrow">АРХИВ</div><h2>Моя история</h2></section><div class="history-list">${state.history.length?state.history.map(h=>`<article class="history-item"><div><span>${esc(h.topic)}</span><small>${esc(h.date)}</small></div><p>${esc(h.observation)}</p></article>`).join(""):`<p class="empty">Здесь будут появляться завершённые исследования.</p>`}</div></div>`}
function bind(){document.querySelectorAll("[data-action]").forEach(b=>b.onclick=e=>{if(b.dataset.stop)e.stopPropagation();const a=b.dataset.action;if(a==="start")go("topic");if(a==="home")go("home");if(a==="topic")go("topic");if(a==="history")go("history");if(a==="context-next"||a==="context-skip"){state.context=a==="context-next"?(document.getElementById("context")?.value.trim()||""):"";const pool=cards.filter(c=>c.topics?.includes(state.topic));state.card=(pool.length?pool:cards)[Math.floor(Math.random()*(pool.length?pool.length:cards.length))];state.cardRevealed=false;go("reveal")}if(a==="draw"){state.cardRevealed=true;render()}if(a==="continue"){state.questions=buildQuestionPlan(state.topic);state.qIndex=0;state.answers=[];state.draftAnswer="";go("questions")}if(a==="view-card"){state.draftAnswer=document.getElementById("answer")?.value||state.draftAnswer;state.showCard=true;render()}if(a==="close-card"){state.draftAnswer=document.getElementById("answer")?.value||state.draftAnswer;state.showCard=false;render()}if(a==="answer-next"){const el=document.getElementById("answer"),val=el?.value.trim()||"";if(!val){el?.focus();return}state.answers.push(val);state.draftAnswer="";if(state.qIndex>=state.questions.length-1)go("result");else{state.qIndex++;go("questions")}}if(a==="save")saveSession();if(a==="share")shareResult();if(a==="restart"){state.context="";state.card=null;state.cardRevealed=false;go("topic")}});document.querySelectorAll("[data-topic]").forEach(b=>b.onclick=()=>{state.topic=b.dataset.topic==="random"?TOPICS[Math.floor(Math.random()*(TOPICS.length-1))].id:b.dataset.topic;go("context")})}
function saveSession(){const r=makeResult(),t=topicById(state.topic),item={topic:t.title,date:new Date().toLocaleString("ru-RU",{dateStyle:"medium",timeStyle:"short"}),observation:r.observation};state.history=[item,...state.history].slice(0,30);localStorage.setItem("mak_history",JSON.stringify(state.history));alert("Исследование сохранено.")}
function loadHistory(){try{return JSON.parse(localStorage.getItem("mak_history")||"[]")}catch(e){return[]}}
async function shareResult(){const r=makeResult(),text=`МАК — моя история\n\n${r.observation}\n\n${r.question}`;try{if(navigator.share){await navigator.share({title:"МАК — моя история",text});return}await navigator.clipboard.writeText(text);alert("Текст скопирован.")}catch(e){}}
render();